### PR TITLE
Bump nvmrc to 10 for netlify

### PR DESCRIPTION
**Pull request by thedamon**
I tried deploying a site based on this repo to netlify and it failed due to a node mismatch. This got the build to work. From the logs I _think_ it's due to them now using a newer version of yarn the requires a newer node? 

```
1:21:28 PM: > Successfully installed Yarn 1.17.0! Please open another terminal where the `yarn` command will now be available.
1:21:28 PM: Installing NPM modules using Yarn version 1.17.0
1:21:29 PM: yarn install v1.17.0
1:21:29 PM: [1/4] Resolving packages...
1:21:29 PM: [2/4] Fetching packages...
1:21:38 PM: error semver@7.3.2: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
1:21:38 PM: error Found incompatible module.
1:21:38 PM: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
1:21:38 PM: Error during Yarn install
1:21:38 PM: Error running command: Build script returned non-zero exit code: 1
1:21:38 PM: Failing build: Failed to build site
1:21:38 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
1:21:39 PM: Finished processing build request in 21.240330682s
```

### CODE REVIEW

**Comment by alexnm** [comment]
Hey, I came here to suggest a similar update, I encountered issues with the eleventy-plugin-lazy-images on node 8.

Still, shouldn't this be bumped to v12 directly? and there's a node version in .travis.yml as well.

**Comment by thedamon** [comment]
I can't actually recall why I chose 11, though I feel like I had a reason when I hastily put this together 😀

**Comment by d2s** [comment]
Using Node.js v12 (`12` on the `.nvmrc` file) would probably make sense, because v10 is in a maintenance mode, and has EOL in a year (2021-04-30).

[Releases | Node.js](https://nodejs.org/en/about/releases/) page has this chart at the moment of writing:

2020-05-15-1702-Node js-release-schedule

**Comment by zachleat** [comment]
Merged but I would merge a `12` too 😅

**Pull request merged**
