### PR TITLE
Nicer font

### PR DESCRIPTION
**Pull request by krzychukula**
Taken from: https://bitsofco.de/the-new-system-font-stack/

### CODE REVIEW

**Comment by zachleat** [comment]
Ah, I’m on board with this but I think we can probably just use `system-ui, sans-serif` right? Seems to hit the right simplicity/support tradeoffs for me: https://caniuse.com/#feat=font-family-system-ui

**Comment by krzychukula** [comment]
I remember reading about some problems with it. It was some time ago, so I had to google a little bit. 
https://infinnie.github.io/blog/2017/systemui.html

I'm not up to date with the issue, but I would have a hard time checking it myself (and my googlefu didn't result in anything making it clearer).

You're right that it looks a lot simpler. Please let me know if I should update the PR?

**Comment by zachleat** [comment]
Thanks for that research!

Related links from your link:
* https://github.com/w3c/csswg-drafts/issues/3658
* https://bugs.chromium.org/p/chromium/issues/detail?id=554590#c21

Will those in mind if you do still want to update the PR to `system-ui, sans-serif` I will merge it! Thanks!

**Comment by zachleat** [comment]
Thanks!

**Pull request merged**
