### PR TITLE
Adding url encode filter to make encoding simpler

### PR DESCRIPTION
**Pull request by spekulatius**
Adding url encoding for URL in meta tags and open graph tags.

### CODE REVIEW

**Comment by zachleat** [comment]
Ah, I don’t want to add anything that isn’t actively being used in the templates here. Is there a good example we can add to the templates where this would be useful?

**Comment by spekulatius** [comment]
Hey @zachleat 

I use it to encode URL parameters for imageee.com - a free social image generation service. For example on this article: https://peterthaleikis.com/business-idea-validation/

Peter

**Comment by zachleat** [comment]
Sorry—I think this might be better served as a plugin rather than a base blog addition. Thank you!

**Comment by spekulatius** [comment]
Okay 👍️

**Pull request closed without merging**
