### PR TITLE
Add 'remix on glitch' link to readme

### PR DESCRIPTION
**Pull request by clottman**
Working port of this project on glitch.com at https://glitch.com/~11ty-eleventy-base-blog.

### CODE REVIEW

**Comment by clottman** [comment]
@zachleat bump! :)

**Comment by zachleat** [comment]
Hey @clottman sorry I am so late here. What’s the best way to keep this glitch up to date? Seems like it might be outdated

**Comment by zachleat** [comment]
I am still interested in merging this @clottman! I also noticed that this project _was_ updated to 0.10.0 but I would like to know how or who is managing that? If it needs to be me that’s fine too just want to make sure it’s always up to date or get a better strategy around keeping it up to date.

**Comment by clottman** [comment]
Hi Zach! I'm the one updating it - I updated the version in package.json and wanted to merge in the rest of the changes from this repo, but there were merge conflicts and I got distracted. 

I can take another look at getting it updated though; I'll comment here when finished.

**Comment by clottman** [comment]
Ok @zachleat all up-to-date with this repository!

**Comment by zachleat** [comment]
Thank you!

**Pull request merged**
